import type { AgentSpec } from "./types";
import type { AdkTool } from "./adk-parser";

export type SandboxStepLog = {
  step: number;
  thought?: string;
  tool?: string;
  input?: any;
  output?: any;
  durationMs: number;
  status: "ok" | "error" | "simulated";
};

export type SandboxRunResult = {
  agentName: string;
  engine: "gemini" | "claude" | "simulation";
  model: string;
  output: string;
  steps: SandboxStepLog[];
  durationMs: number;
  usage?: { inputTokens: number; outputTokens: number };
};

/**
 * Generates realistic mock responses for ADK tools during sandbox experimentation.
 */
function mockToolResponse(toolName: string, input: any): any {
  const t = toolName.toLowerCase();

  if (t.includes("order") || t.includes("customer")) {
    return {
      status: "success",
      customer_id: input.customer_id || "CUST-98214",
      order_id: input.order_id || "ORD-2026-8819",
      items: [
        { sku: "SKU-992", name: "Premium Enterprise Hardware Hub", quantity: 1, amount: 249.0, deliveryStatus: "Delivered Damaged" },
      ],
      eligible_for_refund: true,
      suggested_refund_amount: 249.0,
    };
  }

  if (t.includes("refund") || t.includes("payment") || t.includes("transfer")) {
    return {
      refund_reference: "RF-" + Math.floor(100000 + Math.random() * 900000),
      order_id: input.order_id || "ORD-2026-8819",
      amount_refunded: input.amount || 249.0,
      method: "Original Payment (Visa ending in 4019)",
      timestamp: new Date().toISOString(),
      status: "AUTHORIZED",
    };
  }

  if (t.includes("ledger") || t.includes("transaction") || t.includes("sql")) {
    return {
      query: input.sql || "SELECT * FROM general_ledger WHERE amount >= 10000",
      rowCount: 3,
      rows: [
        { entry_id: "JE-88210", account: "9910-SUSPENSE", amount: 45000.0, poster: "svc-admin", date: "2026-09-06 (Sunday)", risk_score: 4 },
        { entry_id: "JE-88219", account: "6020-EXPENSE", amount: 15000.0, poster: "j.doe", date: "2026-09-08", risk_score: 1 },
        { entry_id: "JE-88225", account: "1010-CASH", amount: 50000.0, poster: "svc-admin", date: "2026-09-09", risk_score: 3 },
      ],
    };
  }

  if (t.includes("upload") || t.includes("s3") || t.includes("storage")) {
    return {
      uploaded: true,
      storage_uri: "s3://enterprise-audit-vault/reports/" + (input.filename || "audit-memo.md"),
      sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      size_bytes: 3420,
    };
  }

  if (t.includes("log") || t.includes("inspect") || t.includes("metric")) {
    return {
      service: input.serviceName || "auth-service",
      p99_latency_ms: 4120,
      error_rate_percent: 14.8,
      primary_exception: "ConnectionPoolExhaustionException: pool size 50 exceeded waiting queue 200",
      recommended_action: "Increase DB max_connections pool or scale replicas",
    };
  }

  if (t.includes("slack") || t.includes("teams") || t.includes("notify") || t.includes("alert")) {
    return {
      delivered: true,
      channel: "#devops-incident-sev1",
      broadcast_timestamp: new Date().toISOString(),
      recipients_notified: 8,
    };
  }

  return {
    success: true,
    tool: toolName,
    receivedInput: input,
    mockNote: "Automated realistic response generated by Agent Studio ADK Sandbox.",
  };
}

/**
 * Executes an ADK agent using Google Gemini REST API.
 */
async function runGeminiSandbox(opts: {
  spec: AgentSpec;
  tools: AdkTool[];
  input: string;
  geminiApiKey: string;
  model: string;
}): Promise<SandboxRunResult> {
  const { spec, tools, input, geminiApiKey, model } = opts;
  const targetModel = model.startsWith("gemini") ? model : "gemini-2.5-flash";
  const startTotal = Date.now();

  const functionDeclarations = tools.map((t) => ({
    name: t.name,
    description: t.description || `Function ${t.name}`,
    parameters: {
      type: "OBJECT",
      properties: Object.fromEntries(
        Object.entries(t.parameters?.properties || {}).map(([k, v]: [string, any]) => [
          k,
          {
            type: v.type?.toUpperCase() === "NUMBER" ? "NUMBER" : v.type?.toUpperCase() === "BOOLEAN" ? "BOOLEAN" : "STRING",
            description: v.description || k,
          },
        ])
      ),
      required: t.parameters?.required || [],
    },
  }));

  const systemInstruction = {
    parts: [
      {
        text: `You are "${spec.name}", a Google ADK agent running in Agent Studio.\n\nPROCEDURE:\n${spec.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}\n\nGUARDRAILS:\n- Follow instructions strictly.\n- Always invoke the appropriate tool before making claims.`,
      },
    ],
  };

  const contents: any[] = [
    {
      role: "user",
      parts: [{ text: input || "Execute the agent procedure." }],
    },
  ];

  const steps: SandboxStepLog[] = [];
  let currentTurn = 0;
  let finalOutput = "";

  while (currentTurn < 8) {
    currentTurn++;
    const stepStart = Date.now();

    const payload: any = {
      system_instruction: systemInstruction,
      contents,
      generationConfig: {
        temperature: 0.2,
        maxOutputTokens: 2048,
      },
    };

    if (functionDeclarations.length) {
      payload.tools = [{ functionDeclarations }];
    }

    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${targetModel}:generateContent?key=${geminiApiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
        signal: AbortSignal.timeout(25000),
      }
    );

    const data = await res.json();
    if (!res.ok) {
      throw new Error(data.error?.message || `Gemini API returned HTTP ${res.status}`);
    }

    const candidate = data.candidates?.[0]?.content;
    if (!candidate) {
      break;
    }

    contents.push(candidate);

    const parts = candidate.parts || [];
    const functionCallPart = parts.find((p: any) => p.functionCall);
    const textPart = parts.find((p: any) => p.text);

    if (textPart) {
      finalOutput = textPart.text;
    }

    if (functionCallPart) {
      const fn = functionCallPart.functionCall;
      const toolOutput = mockToolResponse(fn.name, fn.args);

      steps.push({
        step: currentTurn,
        thought: textPart ? textPart.text : `Calling Google ADK tool: ${fn.name}`,
        tool: fn.name,
        input: fn.args,
        output: toolOutput,
        durationMs: Date.now() - stepStart,
        status: "ok",
      });

      contents.push({
        role: "function",
        parts: [
          {
            functionResponse: {
              name: fn.name,
              response: toolOutput,
            },
          },
        ],
      });
    } else {
      // Finished
      break;
    }
  }

  return {
    agentName: spec.name,
    engine: "gemini",
    model: targetModel,
    output: finalOutput || "Procedure completed successfully.",
    steps,
    durationMs: Date.now() - startTotal,
  };
}

/**
 * Runs an ADK agent via Anthropic Claude cross-compilation.
 */
async function runClaudeSandbox(opts: {
  spec: AgentSpec;
  tools: AdkTool[];
  input: string;
  claudeApiKey: string;
}): Promise<SandboxRunResult> {
  const { spec, tools, input, claudeApiKey } = opts;
  const startTotal = Date.now();

  const claudeTools = tools.map((t) => ({
    name: t.name,
    description: t.description || `Tool ${t.name}`,
    input_schema: t.parameters || { type: "object", properties: {}, required: [] },
  }));

  const systemPrompt = `You are "${spec.name}", an agent authored with Google ADK running in Agent Studio.\n\nPROCEDURE:\n${spec.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}\n\nCall tools appropriately to complete the goal.`;

  const messages: any[] = [{ role: "user", content: input || "Execute the agent procedure." }];
  const steps: SandboxStepLog[] = [];
  let currentStep = 0;
  let finalOutput = "";

  while (currentStep < 8) {
    currentStep++;
    const stepStart = Date.now();

    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": claudeApiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6",
        max_tokens: 2048,
        system: systemPrompt,
        tools: claudeTools.length ? claudeTools : undefined,
        messages,
      }),
      signal: AbortSignal.timeout(25000),
    });

    const data = await res.json();
    if (!res.ok) {
      throw new Error(data.error?.message || `Anthropic API returned HTTP ${res.status}`);
    }

    const content = data.content || [];
    messages.push({ role: "assistant", content });

    const textBlocks = content.filter((b: any) => b.type === "text").map((b: any) => b.text).join("\n");
    if (textBlocks) finalOutput = textBlocks;

    const toolUses = content.filter((b: any) => b.type === "tool_use");
    if (!toolUses.length || data.stop_reason === "end_turn") {
      break;
    }

    const toolResults: any[] = [];
    for (const tu of toolUses) {
      const toolOutput = mockToolResponse(tu.name, tu.input);
      steps.push({
        step: currentStep,
        thought: textBlocks || `Invoking tool ${tu.name}`,
        tool: tu.name,
        input: tu.input,
        output: toolOutput,
        durationMs: Date.now() - stepStart,
        status: "ok",
      });

      toolResults.push({
        type: "tool_result",
        tool_use_id: tu.id,
        content: JSON.stringify(toolOutput),
      });
    }

    messages.push({ role: "user", content: toolResults });
  }

  return {
    agentName: spec.name,
    engine: "claude",
    model: process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6",
    output: finalOutput || "Procedure completed successfully.",
    steps,
    durationMs: Date.now() - startTotal,
  };
}

/**
 * High-fidelity deterministic simulator when no live API keys are present.
 */
function runSimulatedSandbox(spec: AgentSpec, tools: AdkTool[], input: string): SandboxRunResult {
  const start = Date.now();
  const steps: SandboxStepLog[] = [];

  // Simulate tool calls according to the agent's parsed steps & tools
  let stepIdx = 0;
  for (const t of tools.slice(0, 3)) {
    stepIdx++;
    const mockOutput = mockToolResponse(t.name, { inputPrompt: input });
    steps.push({
      step: stepIdx,
      thought: `Step ${stepIdx}: Formulated requirement based on instruction and preparing call to ${t.name}`,
      tool: t.name,
      input: { query: input, target: "production-data" },
      output: mockOutput,
      durationMs: 40 + Math.floor(Math.random() * 80),
      status: "simulated",
    });
  }

  const output = `### ${spec.name} Execution Deliverable

**Status**: Verified & Successfully Completed  
**Archetype**: \`${spec.archetype}\`  
**Input Processed**: "${input}"  

#### Key Actions & Findings:
${spec.steps.map((s, i) => `${i + 1}. **${s}** — Executed and validated against sandbox data.`).join("\n")}

#### Tool Telemetry Summary:
${steps.map((s) => `- \`${s.tool}\`: Returned status \`${s.output?.status || "OK"}\` in ${s.durationMs}ms`).join("\n")}

> *Simulated sandbox trace generated by Agent Studio ADK Sandbox. Provide a Google Gemini or Anthropic API key to run against live foundational LLM endpoints.*`;

  return {
    agentName: spec.name,
    engine: "simulation",
    model: "gemini-2.5-flash (sandbox)",
    output,
    steps,
    durationMs: Date.now() - start,
  };
}

/**
 * Main sandbox execution runner.
 */
export async function executeSandboxRun(opts: {
  spec: AgentSpec;
  tools: AdkTool[];
  input: string;
  preferredEngine?: "gemini" | "claude" | "auto";
  geminiApiKey?: string;
  claudeApiKey?: string;
  model?: string;
}): Promise<SandboxRunResult> {
  const { spec, tools, input, preferredEngine = "auto", geminiApiKey, claudeApiKey, model } = opts;

  // 1. Try Gemini if key is available or requested
  if ((preferredEngine === "gemini" || preferredEngine === "auto") && geminiApiKey) {
    try {
      return await runGeminiSandbox({
        spec,
        tools,
        input,
        geminiApiKey,
        model: model || "gemini-2.5-flash",
      });
    } catch (err) {
      console.warn("Gemini sandbox run failed, falling back to simulated engine:", err);
    }
  }

  // 2. Try Claude if key is available
  if ((preferredEngine === "claude" || preferredEngine === "auto") && (claudeApiKey || process.env.ANTHROPIC_API_KEY)) {
    try {
      return await runClaudeSandbox({
        spec,
        tools,
        input,
        claudeApiKey: claudeApiKey || process.env.ANTHROPIC_API_KEY || "",
      });
    } catch (err) {
      console.warn("Claude sandbox run failed, falling back to simulated engine:", err);
    }
  }

  // 3. Realistic sandbox simulation
  return runSimulatedSandbox(spec, tools, input);
}
