import { NextRequest, NextResponse } from "next/server";
import { one, q } from "@/lib/db";
import { getUser } from "@/lib/auth";
import { startRun } from "@/lib/orchestrator";
import { maskPII, checkRateLimit } from "@/lib/guardrails";
import type { AgentSpec } from "@/lib/types";

export const runtime = "nodejs";
export const maxDuration = 300;

function corsHeaders() {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization, X-API-Key",
  };
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: corsHeaders(),
  });
}

/**
 * GET /api/v1/agents/{id}/invoke
 * Returns OpenAPI 3.0 specification for this agent
 */
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: agentId } = await params;
  const agent = await one<any>(`select * from agents where id = $1`, [agentId]);
  if (!agent) {
    return NextResponse.json({ error: "Agent not found" }, { status: 404, headers: corsHeaders() });
  }

  const spec: AgentSpec = agent.published_ver
    ? (await one<any>(`select spec from agent_versions where agent_id = $1 and version = $2`, [agentId, agent.published_ver]))?.spec || agent.draft_spec
    : agent.draft_spec;

  const openApiSpec = {
    openapi: "3.0.3",
    info: {
      title: `${agent.name} - Agent Studio API`,
      description: spec.purpose || `Automated autonomous agent: ${agent.name}`,
      version: String(agent.published_ver || 1),
    },
    servers: [{ url: "/api/v1" }],
    paths: {
      [`/agents/${agentId}/invoke`]: {
        post: {
          summary: `Invoke ${agent.name}`,
          description: `Execute an autonomous run of ${agent.name} with custom input prompt and parameter values.`,
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    input: {
                      type: "string",
                      description: "Primary user prompt or instruction to direct the agent.",
                      example: "Analyze data and execute assigned procedure.",
                    },
                    parameters: {
                      type: "object",
                      description: "Optional key-value inputs configured on the agent spec.",
                      additionalProperties: true,
                    },
                    dryRun: {
                      type: "boolean",
                      description: "If true, simulates agent reasoning without executing external side-effect tools.",
                      default: false,
                    },
                  },
                  required: ["input"],
                },
              },
            },
          },
          responses: {
            "200": {
              description: "Successful agent run execution",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: {
                      agentId: { type: "string" },
                      agentName: { type: "string" },
                      runId: { type: "string" },
                      status: { type: "string", example: "completed" },
                      output: { type: "string", description: "Final deliverable generated by the agent." },
                      stepsCount: { type: "integer" },
                      toolsCalled: { type: "array", items: { type: "string" } },
                      usage: {
                        type: "object",
                        properties: {
                          inputTokens: { type: "integer" },
                          outputTokens: { type: "integer" },
                          costUsd: { type: "number" },
                        },
                      },
                      durationMs: { type: "integer" },
                    },
                  },
                },
              },
            },
            "429": {
              description: "Per-agent rate limit exceeded (RPM or TPM)",
            },
          },
        },
      },
    },
  };

  return NextResponse.json(openApiSpec, { headers: corsHeaders() });
}

/**
 * POST /api/v1/agents/{id}/invoke
 * Standalone REST invocation endpoint
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: agentId } = await params;
  const t0 = Date.now();

  const agent = await one<any>(`select * from agents where id = $1`, [agentId]);
  if (!agent) {
    return NextResponse.json({ error: "Agent not found" }, { status: 404, headers: corsHeaders() });
  }

  if (agent.status === "retired") {
    return NextResponse.json(
      { error: "This agent is retired and cannot be invoked." },
      { status: 409, headers: corsHeaders() }
    );
  }

  // Resolve user authentication (Bearer token, X-API-Key, or active cookie session)
  const authHeader = req.headers.get("authorization") || "";
  const apiKeyHeader = req.headers.get("x-api-key") || "";
  const user = await getUser();

  const callerName = user?.name || (authHeader ? "API Token Client" : "External REST Client");
  const callerId = user?.id || agent.org_id;

  // Resolve spec
  let spec: AgentSpec = agent.draft_spec;
  let version: number | null = null;
  if (agent.published_ver) {
    const v = await one<any>(
      `select spec, version from agent_versions where agent_id = $1 and version = $2`,
      [agentId, agent.published_ver]
    );
    if (v) {
      spec = v.spec;
      version = v.version;
    }
  }

  // 1. Enforce Per-Agent Rate Limiting
  const rateLimitRpm = spec.guardrails?.rateLimitRpm || 60;
  const rateLimitTpm = spec.guardrails?.rateLimitTpm;
  const rateCheck = checkRateLimit(agentId, rateLimitRpm, rateLimitTpm);
  if (!rateCheck.allowed) {
    return NextResponse.json(
      {
        error: "Too Many Requests",
        message: `Rate limit of ${rateLimitRpm} RPM exceeded for ${agent.name}.`,
        retryAfterSeconds: rateCheck.retryAfterSeconds,
      },
      {
        status: 429,
        headers: {
          ...corsHeaders(),
          "Retry-After": String(rateCheck.retryAfterSeconds),
        },
      }
    );
  }

  // Parse Body
  let body: any = {};
  try {
    body = await req.json();
  } catch {
    body = {};
  }

  const rawInput = body.input || body.prompt || "Execute assigned agent procedure.";
  const inputs = body.parameters || body.inputs || {};
  const dryRun = Boolean(body.dryRun);

  // 2. Apply DLP & PII Masking
  let effectiveInput = rawInput;
  let dlpDetections: any[] = [];
  if (spec.guardrails?.dlpEnabled) {
    const dlpResult = maskPII(rawInput, {
      enabled: true,
      redactCreditCards: spec.guardrails.redactCreditCards,
      redactEmails: spec.guardrails.redactEmails,
      redactCredentials: spec.guardrails.redactCredentials,
      redactPhoneNumbers: spec.guardrails.redactPhoneNumbers,
      customPatterns: spec.guardrails.customDlpPatterns,
    });
    effectiveInput = dlpResult.text;
    dlpDetections = dlpResult.detections;
  }

  try {
    // Start and advance the run
    const runId = await startRun({
      orgId: agent.org_id,
      agentId,
      spec,
      version,
      input: effectiveInput,
      user: { id: callerId, name: callerName },
      trigger: "api",
      dryRun,
      inputs,
    });

    // Fetch the run output and metrics
    const runRecord = await one<any>(`select * from runs where id = $1`, [runId]);
    const steps = await q<any>(
      `select idx, kind, tool, title, output, status, duration_ms from run_steps where run_id = $1 order by idx asc`,
      [runId]
    );

    const toolsCalled = steps.filter((s) => s.tool).map((s) => s.tool);
    let output = runRecord?.output || "Run initiated and processing in background.";

    // Apply output DLP masking if enabled
    if (spec.guardrails?.dlpEnabled && output) {
      output = maskPII(output, spec.guardrails).text;
    }

    const durationMs = Date.now() - t0;

    return NextResponse.json(
      {
        agentId,
        agentName: agent.name,
        version: version || 1,
        runId,
        status: runRecord?.status || "completed",
        output,
        stepsCount: steps.length,
        toolsCalled,
        dlp: {
          applied: Boolean(spec.guardrails?.dlpEnabled),
          inputDetections: dlpDetections,
        },
        usage: {
          model: runRecord?.model || "claude-sonnet-4-6",
          inputTokens: runRecord?.input_tokens || 0,
          outputTokens: runRecord?.output_tokens || 0,
          costUsd: Number(runRecord?.cost_usd || 0),
        },
        durationMs,
      },
      { headers: corsHeaders() }
    );
  } catch (err: any) {
    console.error(`[API Invoke Error: ${agent.name}]`, err);
    return NextResponse.json(
      {
        error: "Invocation failed",
        detail: err.message || String(err),
      },
      { status: 500, headers: corsHeaders() }
    );
  }
}
