/**
 * Fifty finance and accounting skills corresponding to the Agent Studio agent library.
 *
 * Each skill represents workspace know-how and standard operating procedures (SOPs).
 * While tools provide capability, skills provide instructions on how work is done,
 * calculation rules, verification criteria, and edge-case handling.
 */

export const SKILLS = [
  /* ── 1. Financial Close ───────────────────────────────────────── */
  {
    agentName: "Month-End Close Conductor",
    label: "Month-End Close Task Orchestration",
    description: "Use when evaluating financial close checklist progress, calculating task slippage, identifying bottleneck owners, or assembling status summaries.",
    instructions: `## Purpose & Scope
This skill governs the orchestration, tracking, and escalation of period-end financial close activities across corporate accounting, reporting, tax, and divisional controllership teams.

## Close Phase Milestones
1. **Pre-Close (T-3 to T-0):** Subledger cut-offs (AP, AR, Fixed Assets, Inventory freeze), payroll feeds verification, and initial bank feeds pull.
2. **Core Subledger Close (T+1 to T+2):** Billing run completion, cash application lock, supplier invoice accrual estimates, and preliminary inventory valuation.
3. **General Ledger & Intercompany (T+3 to T+4):** Elimination entries, recurring journals, corporate overhead allocations, and foreign currency revaluations.
4. **Financial Statement Finalization (T+5 to T+7):** Trial balance lock, balance sheet reconciliations review, variance sign-offs, and executive reporting pack freeze.

## Task Status Classification & Arithmetic
- **Complete:** Explicitly recorded as completed in the close tracking system with sign-off timestamp and preparer ID.
- **Due Today:** Target date equals current system date and status is open/in-progress.
- **Overdue (Critical):** Target date is prior to current system date and status is not complete.
  - Calculate slippage in working days: \`Slippage = CurrentDate - TargetDate\` (excluding official company holidays and weekends).
  - High criticality flag: Any task on the critical path (e.g., Subledger Lock, Intercompany Settlement) that is >1 working day overdue.

## Escalation & Communication Rules
- Group checklist output strictly by status priority: Overdue first, followed by Due Today, then In Progress, then Complete.
- For each overdue item, clearly specify: Task Title, Workstream/Entity, Task Owner, Target Due Date, Working Days Slipped, and Dependent Downstream Milestones.
- Lead all notifications with aggregate summary metrics: Total Tasks, Completed %, Overdue Count, Due Today Count.`
  },
  {
    agentName: "Journal Entry Anomaly Reviewer",
    label: "Journal Entry Risk & Anomaly Screening",
    description: "Use when auditing journal entry listings for unusual posting characteristics, cut-off irregularities, round sums, or unauthorized manual overrides.",
    instructions: `## Purpose & Scope
Provides forensic and risk-based screening criteria for manual and recurring general ledger journal entries to support Sarbanes-Oxley (SOX), statutory compliance, and internal audit oversight.

## Key Risk Patterns & Detection Rules
1. **Suspiciously Round Amounts:**
   - Filter entries where the absolute transaction amount equals multiples of 1,000, 10,000, 50,000, or 100,000 (e.g., amount % 1000 = 0).
   - Flag round-dollar adjustments to expense or suspense accounts within 5 days of period close.
2. **Weekend & Non-Working Hour Postings:**
   - Detect postings with timestamps occurring on Saturdays, Sundays, or outside standard business operating hours (before 07:00 or after 20:00 local posting entity time).
3. **Super-User & Infrequent Poster Activity:**
   - Highlight entries generated by system administrators, service accounts, or users whose historical volume averages less than 2 entries per quarter.
4. **Dormant & High-Risk Account Hits:**
   - Flag debits or credits hitting accounts that had zero posting activity for >180 days.
   - Screen for entries impacting Cash, Retained Earnings, Goodwill, or Suspense accounts that lack secondary approval tags.
5. **Period-End Cut-off Acceleration / Deferral:**
   - Scrutinize manual entries booked within 48 hours before or after the GL balance freeze date, especially reversal entries scheduled for the first business day of the subsequent month.

## Scoring & Scoring Matrix
- Calculate risk score per entry:
  - 1 point: Round value.
  - 2 points: Weekend/after-hours posting.
  - 2 points: Low-frequency poster or super-user credential.
  - 3 points: Hit to suspense or equity accounts.
  - 2 points: Immediate reversal flagged on Day 1.
- Flag any entry scoring >= 3 points as 'Priority Review Required'. Formulate questions neutrally as reviewer verification queries rather than accusations.`
  },
  {
    agentName: "Balance Sheet Reconciliation Checker",
    label: "Balance Sheet Account Reconciliation Standard",
    description: "Use when validating balance sheet substantiation schedules, recalculating line items against ledger balances, or categorizing unexplained reconciling differences.",
    instructions: `## Purpose & Scope
Establishes the standard operating procedure for reviewing and validating monthly balance sheet account reconciliations to ensure financial records are complete, accurate, and properly substantiated.

## Substantiation Standards
1. **Ledger Balance Alignment:**
   - The reconciliation header must draw directly from the closing general ledger balance at the exact period cut-off date.
   - Any divergence between the reconciliation starting point and the trial balance is an immediate hard stop defect.
2. **Supporting Documentation Validity:**
   - Every reconciling line item must have third-party documentation or mathematical derivation (bank statements, vendor statements, inventory subledger, amortisation schedules).
   - Generic labels such as 'reconciling difference', 'timing difference', or 'adjusting balance' without invoice/reference details are unacceptable.

## Arithmetic & Ageing Verification
- **Recalculation:**
  \`Ledger Balance + Total Debits/Adjustments - Total Credits/Adjustments = Reconciled Target Balance\`
  - Net unexplained difference must equal 0.00. Any difference > 0.01 must be prominently flagged in the conclusion line.
- **Ageing Categorisation:**
  - 0-30 Days: Normal operating transit / current timing difference.
  - 31-60 Days: Requires active review; request comment from owner.
  - 61-90 Days: Elevated risk; requires root-cause explanation.
  - >90 Days: Stale reconciling item. Must be evaluated for immediate P&L write-off or provision accrual under GAAP/IFRS conservatism principles.

## Deliverable Format
- Header: Account Number, Account Name, Entity, Period, Preparer, Approver.
- Arithmetic agreement confirmation (Pass/Fail).
- Tabular breakdown of reconciling items with columns: Item Ref, Description, Date Originated, Age (Days), Amount, Supporting Evidence Link.
- Immediate action items for unexplained differences.`
  },
  {
    agentName: "Accrual Completeness Tester",
    label: "Cut-off & Unrecorded Accrual Review",
    description: "Use when identifying unrecorded liabilities, reviewing post-period accounts payable disbursements, or comparing subsequent invoices against accrued expenses.",
    instructions: `## Purpose & Scope
Governs the testing of completeness for accrued expenses and accounts payable at period close, preventing understatement of liabilities and operating expenses.

## Identification & Matching Workflow
1. **Extract Post-Period Invoices:**
   - Pull all supplier invoices entered or approved within 30 to 45 calendar days following the period balance sheet cut-off date.
2. **Determine Economic Service Period:**
   - Review invoice service dates, line descriptions, goods receipt notes (GRNs), or bill of lading delivery dates.
   - Rule: If goods were received or services rendered on or prior to the balance sheet date, the economic obligation belongs in the closed period.
3. **Cross-Check Accrual Register:**
   - Check whether the supplier, PO number, or specific expense line was already provided for on the period-end AP accrual schedule or PO accrual listing.
   - Verify if the invoice was matched against an un-invoiced GRN (GR/IR clearing account).

## Exception Thresholds & Risk Ranking
- **Confirmed Unrecorded Liability:** Service period <= cut-off date, and no corresponding accrual exists on the accrual schedule.
  - Materiality Filter: Highlight all unrecorded items exceeding $5,000 (or departmental materiality threshold).
- **Under-Accrual:** Accrual existed but was less than the actual invoice by >15% and >$2,500.
- **Timing Misallocation:** Invoice booked into prior period but service delivered in subsequent period (prepayment misclassified as expense).

## Output Specification
Produce a clear report listing: Invoice Number, Supplier Name, Invoice Date, Service Period From/To, Invoice Gross Amount, Existing Accrual Amount, Net Variance (Unrecorded Exposure), and Recommended Adjustment Entry (Debit Expense / Credit Accrued Liabilities).`
  },
  {
    agentName: "Intercompany Mismatch Finder",
    label: "Intercompany Balance Matching & Elimination",
    description: "Use when reconciling bilateral intercompany balances, identifying transactional currency mismatches, or isolating transit items prior to consolidation elimination.",
    instructions: `## Purpose & Scope
Sets forth the protocol for bilateral and multilateral intercompany balance reconciliation between parent, subsidiary, and affiliate legal entities to ensure zero net variance upon consolidation.

## Reconciliation Protocol
1. **Entity Pairing:**
   - Pair Entity A's Due From Entity B (Asset) against Entity B's Due To Entity A (Liability).
   - Invert balances to verify that: \`Entity_A_Receivable + Entity_B_Payable = 0.00\`.
2. **Currency Standardization:**
   - Reconcile first in transaction currency (original invoicing currency).
   - Then reconcile in group reporting currency using standard month-end corporate FX closing rates.
   - Differentiate between true transaction disputes and FX revaluation variance.
3. **Common Mismatch Drivers to Test:**
   - **In-Transit Shipments / Cash:** One entity recorded billing/payment before cut-off while counterparty booked after cut-off.
   - **Disputed Cross-Charges:** Central management fees or IT allocations recorded by parent but disputed or unposted by subsidiary.
   - **Tax/Withholding Discrepancies:** Gross amount billed by creditor vs net amount accrued by debtor due to local withholding tax.

## Actionable Escalation Tiers
- **Tier 1 (Within Tolerance):** Net discrepancy < $500 per pairing. Automatically post to intercompany rounding / FX clearing.
- **Tier 2 (Material Timing Difference):** One-sided entry supported by timestamped transit documentation. Record adjusting accrual in lagging entity.
- **Tier 3 (Unmatched / Disputed):** Discrepancy > $5,000 or aged >30 days. Issue formal dispute ticket naming both entity controllers with required resolution deadline.`
  },
  {
    agentName: "Variance Commentary Writer",
    label: "Financial Variance Analysis & Commentary",
    description: "Use when decomposing budget, forecast, or prior-period financial variances into volume, price, mix, and timing components for management reporting.",
    instructions: `## Purpose & Scope
Guides the financial commentary authoring process, transforming raw numeric balance changes into insightful, business-driven management narratives suitable for CFO and Board review.

## Analysis Methodology
1. **Variance Decomposition:**
   - Break down gross revenue and direct margin movement into:
     - **Price Variance:** \`(Actual Price - Budget Price) * Actual Volume\`
     - **Volume Variance:** \`(Actual Volume - Budget Volume) * Budget Price\`
     - **Mix Variance:** Impact of product/regional portfolio skew toward higher/lower margin items.
   - For indirect operating expenses, classify variances into:
     - **Timing:** Expenditure shifted between quarters (e.g., delayed marketing campaign or delayed software license renewal).
     - **Permanent/Rate:** Headcount compensation changes, unbudgeted vendor price increases, or permanent operational expansion.
2. **Materiality Filter:**
   - Focus exclusively on lines that breach the dual threshold: absolute variance > $50,000 AND percentage variance > 10% vs target.

## Narrative Structure Standards
- **Tone:** Objective, crisp, analytical, and forward-looking. Avoid empty descriptions (e.g., 'expenses increased due to higher spending').
- **Standard Paragraph Architecture:**
  - *Headline:* State the metric, movement direction, dollar change, and percentage change.
  - *Root Cause:* Name the operational driver (customer name, project, contract renegotiation, regulatory event).
  - *Impact Analysis:* Clarify whether the effect is recurring, one-off, or timing.
  - *Forward Look & Mitigations:* Outline corrective actions or expected reversal timeline in subsequent quarters.`
  },
  {
    agentName: "Trial Balance Anomaly Scanner",
    label: "Trial Balance Hygiene & Suspense Screening",
    description: "Use when auditing the general ledger trial balance for inverted balance signs, active suspense accounts, unmapped accounts, or unexpected zero balances.",
    instructions: `## Purpose & Scope
Defines systematic trial balance hygiene checks performed prior to financial statement consolidation, preventing balance sheet misclassifications and unassigned balances.

## Key Anomaly Tests
1. **Abnormal / Inverted Account Balances:**
   - Normal Debit Balances: Assets (1xxx), Expenses (5xxx/6xxx). If net balance is credit (negative), flag immediately.
   - Normal Credit Balances: Liabilities (2xxx), Equity (3xxx), Revenues (4xxx). If net balance is debit (positive), flag immediately.
   - Exceptions: Contra accounts (e.g., Accumulated Depreciation, Allowance for Doubtful Accounts, Sales Discounts). Must be validated against known contra-account registry.
2. **Suspense and Clearing Account Exposure:**
   - Inspect all clearing accounts: Payroll Clearing, GR/IR Clearing, Bank In-Transit, Credit Card Settlement, System Migration Suspense.
   - Zero-Balance Rule: Clearing accounts should net to zero upon completion of close cycles. Any non-zero balance must have an ageing schedule.
3. **Dormant Account Incursions:**
   - Flag any account marked 'inactive' or with zero movement for the preceding 6 months that experiences new activity.
4. **Rounding & Currency Translation Discrepancies:**
   - Ensure the total trial balance strictly debits = credits (\`Sum(Debits) - Sum(Credits) = 0.00\`).

## Reporting Requirements
Generate an anomaly report categorizing items by: Account Code, Account Description, Normal Balance Sign, Ending Balance, Nature of Defect, and Assigned Line Reviewer.`
  },
  {
    agentName: "Chart of Accounts Hygiene Auditor",
    label: "Chart of Accounts Governance & Hygiene",
    description: "Use when evaluating chart of accounts structure for naming inconsistencies, redundant duplicate accounts, missing segment tags, or dormant codes.",
    instructions: `## Purpose & Scope
Provides governance standards for maintaining an agile, scalable, and audit-compliant Chart of Accounts (COA) across ERP instances and subsidiary entities.

## Governance Rules & Audit Checks
1. **Naming Standardisation:**
   - Account descriptions must follow standard hierarchy: \`[Category] - [Subcategory] - [Specific Descriptor]\` (e.g., 'OpEx - IT Software - Cloud Hosting SaaS').
   - Flag all uppercase anomalies, typos, placeholder names ('Do Not Use', 'Temp Account', 'Test Acc'), or missing descriptions.
2. **Duplicate & Overlapping Account Detection:**
   - Identify accounts with identical or semantically equivalent descriptions across the same ledger segment (e.g., 'Office Supplies' vs 'Supplies - Office').
   - Screen for fragmented expense accounts that could be consolidated without loss of reporting fidelity.
3. **Dormancy & Decommissioning Criteria:**
   - Flag accounts with zero transactions, zero opening balance, and zero closing balance across the past 12 months.
   - Tag dormant accounts for formal archiving: lock for manual posting, preserve audit history.
4. **Posting Restrictions & Controls:**
   - Header/Summary accounts must be flagged as non-postable.
   - Subledger-controlled control accounts (AP Control, AR Control, Fixed Asset Control) must have manual posting blocked to prevent ledger-to-subledger breakage.

## Output Schedule
Deliver a COA Cleanliness Matrix detailing: Proposed Mergers, Accounts to Lock/Deactivate, Naming Convention Corrections, and Control Account Flag Updates.`
  },

  /* ── 2. Fixed Assets & Accounts Payable ───────────────────────── */
  {
    agentName: "Fixed Asset Register Auditor",
    label: "Fixed Asset Depreciation & Register Audit",
    description: "Use when auditing the fixed asset subledger for depreciation calculation accuracy, fully depreciated assets, asset tagging, and GL reconciliation.",
    instructions: `## Purpose & Scope
Standardizes the periodic audit and reconciliation of the Fixed Asset Register (FAR) against general ledger capital accounts and physical tracking records.

## Audit Procedures & Formulas
1. **Depreciation Accuracy Recalculation:**
   - Straight-Line Depreciation:
     \`Monthly Depreciation = (Capitalized Cost - Estimated Salvage Value) / (Useful Life in Years * 12)\`
   - Recompute depreciation for each asset category (Machinery, Vehicles, IT Hardware, Leasehold Improvements) and compare to ERP subledger runs.
   - Highlight any variance > $1.00 per asset line.
2. **Useful Life & Fully Depreciated Assets:**
   - Identify assets where \`Accumulated Depreciation >= Capitalized Cost\`.
   - Ensure the asset engine halts depreciation once net book value (NBV) equals salvage value.
   - Review active operational status of fully depreciated assets to confirm whether disposal, retirement, or write-off documentation is required.
3. **Subledger to General Ledger Reconciliation:**
   - Reconcile:
     - \`FAR Gross Asset Value == GL Asset Control Account (1500)\`
     - \`FAR Accumulated Depreciation == GL Accumulated Depreciation Account (1550)\`
     - \`FAR Monthly Depreciation Run == GL Depreciation Expense Account (6500)\`
4. **Capitalisation Threshold Verification:**
   - Review additions during the period to verify that all capitalized items meet the corporate threshold (e.g. >= $2,500) and are not expensed repairs.

## Audit Exception Report
Tabulate: Asset ID, Category, In-Service Date, Cost, NBV, Expected Monthly Depreciation, Subledger Monthly Depreciation, Discrepancy Amount, and Remediation Recommendation.`
  },
  {
    agentName: "Invoice Three-Way Match Checker",
    label: "Three-Way Matching & PO Variance Resolution",
    description: "Use when performing three-way verification between vendor invoices, purchase orders, and goods receipt notes, or evaluating price/quantity tolerances.",
    instructions: `## Purpose & Scope
Specifies the automated and manual verification standards for three-way matching (Invoice vs Purchase Order vs Goods Receipt Note) prior to releasing payments.

## Match Criteria & Tolerance Thresholds
1. **Verification Elements:**
   - **PO to Invoice:** Line item descriptions, unit currency, agreed unit price, payment terms, and vendor tax ID.
   - **GRN to Invoice:** Received quantity, acceptance sign-off date, damaged/returned items deduction.
2. **Tolerance Band Policies:**
   - **Quantity Tolerance:** Exact match (0% over-delivery permitted unless explicitly designated as bulk commodity with +/- 5% clause).
   - **Price Variance Tolerance:** Maximum permitted price variance without secondary buyer approval: <= 1.0% of line item value or $25.00 (whichever is lower).
   - **Freight & Incidental Surcharges:** Must be substantiated against contract incoterms (e.g. FOB Destination vs FOB Shipping Point).
3. **Common Hold Classifications:**
   - \`HOLD_QTY\`: Invoice quantity exceeds un-invoiced received quantity.
   - \`HOLD_PRICE\`: Invoice unit price exceeds PO authorized rate.
   - \`HOLD_GRN\`: Invoice arrived but no Goods Receipt has been booked in the system.
   - \`HOLD_TAX\`: Invoiced tax rate does not correspond to delivery jurisdiction rules.

## Resolution Workflow
- For Quantity variances: Route discrepancy notice to Warehouse Receiving.
- For Price variances: Route exception to Procurement Category Buyer for amendment or vendor credit note demand.
- Invoices on hold must be excluded from payment proposal runs until release status is confirmed in the audit trail.`
  },
  {
    agentName: "Duplicate Payment Detector",
    label: "Duplicate Invoice & Disbursement Detection",
    description: "Use when scanning proposed payment runs or accounts payable ledgers for duplicate vendor billings, similar reference numbers, or split payments.",
    instructions: `## Purpose & Scope
Provides forensic algorithms and screening tests to eliminate duplicate supplier disbursements prior to final banking transmission.

## Duplicate Detection Logic
1. **Exact Duplicate Test:**
   - Match condition: Same Vendor ID + Same Exact Invoice Amount + Same Invoice Reference Number.
2. **Fuzzy Reference Number Match:**
   - Match condition: Same Vendor ID + Same Exact Invoice Amount + Normalized Reference Number.
   - Normalization rules: Strip leading zeros ('001234' -> '1234'), remove punctuation, hyphens, and whitespace ('INV-2026/01' -> 'INV202601').
   - Common typographical errors: Transposed digits (e.g. 5834 vs 5843) or appended alpha codes ('A', 'rev').
3. **Vendor Cross-Account Match:**
   - Match condition: Identical Invoice Number + Same Invoice Amount + Different Vendor Account ID, but matching Vendor Tax Identification Number (TIN/VAT) or matching IBAN/Bank Account.
4. **Split Invoicing / Structuring Pattern:**
   - Two or more invoices from the same supplier dated within 48 hours whose sum matches an existing PO or standard payment approval threshold (e.g., two $4,990 invoices avoiding a $5,000 threshold).

## Action Protocol
- Place an immediate payment block (\`BLOCK_DUP\`) on any suspected duplicate line item.
- Generate an AP Exception Dossier showing: Vendor Name, Suspect Invoice ID, Original Invoice ID, Payment Status, Date Comparison, and Required Investigator Action.`
  },
  {
    agentName: "Vendor Master Data Cleanser",
    label: "Vendor Master Record Quality & Fraud Review",
    description: "Use when scrubbing the supplier master file for duplicate entities, inactive accounts, shared banking details, or missing compliance identifiers.",
    instructions: `## Purpose & Scope
Establishes data governance, anti-fraud controls, and hygiene standards for the supplier master database to protect organizational procurement integrity.

## Screening Dimensions & Rules
1. **Duplicate Vendor Detection:**
   - String similarity (Jaro-Winkler or Levenshtein distance > 0.88) on vendor legal names and DBA names.
   - Match on identical Taxpayer Identification Numbers (TIN), VAT/GST registration numbers, or corporate registration numbers.
   - Flag vendors sharing identical postal addresses or email domains.
2. **Internal Fraud & Collusion Screening (Ghost Vendors):**
   - Cross-check vendor bank account routing/IBAN numbers against the employee payroll direct deposit file. Any exact match is a critical fraud alert.
   - Screen vendor addresses against employee residential addresses on file.
   - Flag vendors listing P.O. Box addresses without physical location verification.
3. **Bank Account Modification Controls:**
   - Trace all changes to vendor bank disbursement details within the past 90 days.
   - Verify that dual-custody verification (out-of-band phone callback to validated vendor controller) was logged prior to updating bank credentials.
4. **Dormancy Review:**
   - Tag vendors with no invoice activity for >18 months as 'Inactive - Inactive for Orders'.

## Remediation Deliverable
Provide a Master Data Cleansing Action List: Records recommended for permanent merge, records flagged for deactivation, and high-risk entries requiring anti-fraud verification.`
  },
  {
    agentName: "Supplier Contract Obligation Extractor",
    label: "Commercial Contract Terms & Obligation Extraction",
    description: "Use when reviewing vendor agreements to extract payment terms, indexation clauses, auto-renewal notification windows, and minimum spend commitments.",
    instructions: `## Purpose & Scope
Guides the extraction and commercial structuring of contractual obligations, service level agreements (SLAs), and financial covenants from vendor agreements.

## Target Contract Metadata & Data Points
1. **Commercial Terms:**
   - Base Contract Value, Payment Terms (e.g. Net 30, Net 60, 2% 10 Net 30).
   - Milestone schedule and milestone sign-off criteria.
   - Currency and invoicing mechanics (centralized vs local legal entity).
2. **Escalation & Price Adjustment Clauses:**
   - Indexation rules: Link to CPI, PPI, or labour cost indices; annual cap on price increases (e.g. 'lesser of CPI or 3%').
   - Minimum commitment guarantees and volume tier rebate schedules.
3. **Term, Renewal, and Termination:**
   - Effective Date, Expiration Date, Governing Law.
   - Auto-renewal conditions: Notice period required to prevent renewal (e.g. 60 or 90 days prior written notice).
   - Termination for convenience notice period and associated early termination penalties/fees.
4. **Penalties & Service Credits:**
   - SLA breach calculation rules, service credit caps, liquidated damages provisions.

## Extraction Structure
Produce an obligation schedule with: Contract Identifier, Supplier Legal Entity, Contracting Customer Entity, Start/End Dates, Notice Cut-Off Date, Payment Terms, Annual Committed Spend, Price Increase Formula, and Key Contact/Notice Address.`
  },
  {
    agentName: "Early Payment Discount Optimiser",
    label: "Prompt Payment Discount & Working Capital Optimisation",
    description: "Use when evaluating early payment terms against current cost of capital, optimizing cash release timing, and calculating annualized discount yields.",
    instructions: `## Purpose & Scope
Governs the mathematical assessment and prioritization of early payment discounts (e.g. 2/10 Net 30) against alternative cash deployment and treasury cost of capital.

## Financial Evaluation Formulas
1. **Effective Annualized Yield (EAY) Formula:**
   \`EAY = (Discount % / (100% - Discount %)) * (365 / (Full Due Date - Discount Payment Date))\`
   - *Example for 2/10 Net 30:*
     \`EAY = (2 / 98) * (365 / (30 - 10)) = 0.020408 * 18.25 = 37.24% annualized yield.\`
2. **Hurdle Rate Decision Rule:**
   - Compare calculated EAY against the company's internal treasury benchmark rate (Cost of Capital or short-term credit facility borrowing cost + 200 bps risk spread).
   - **Decision: ACCEPT:** If \`EAY > Benchmark Hurdle Rate\` and working capital liquidity buffer is satisfied.
   - **Decision: REJECT / HOLD:** If \`EAY <= Benchmark Hurdle Rate\` or cash flow is restricted; schedule payment on the final contractual day (Day 30).
3. **Missed Discount Audit:**
   - Calculate forgone cash savings on paid invoices where discount period lapsed due to AP processing bottlenecks:
     \`Forgone Savings = Gross Invoice Amount * Discount %\`.

## Summary Schedule
Present an AP Cash Optimisation Table: Invoice ID, Vendor, Invoice Amount, Terms, Target Discount Date, Net Discount Amount, Annualized Yield %, Recommended Action (Pay Early vs Pay on Due Date).`
  },
  {
    agentName: "Expense Policy Compliance Checker",
    label: "Corporate T&E Policy Compliance Audit",
    description: "Use when reviewing corporate card and employee expense reports for per-diem caps, non-reimbursable items, weekend expenses, and missing receipt attachments.",
    instructions: `## Purpose & Scope
Provides rigorous compliance criteria for employee travel, entertainment, and commercial expense reimbursement in accordance with internal corporate policy and tax deductibility rules.

## Core Policy Violation Patterns
1. **Receipt Verification & Thresholds:**
   - All transactions exceeding $25.00 (or statutory IRS/tax threshold) must have an itemized receipt attached showing merchant name, date, items, and tax breakdown.
   - Credit card charge slips showing only the total amount without line items do not qualify as itemized documentation.
2. **Meal & Per-Diem Limits:**
   - Check meals against maximum per-person meal allowance (Breakfast: $25, Lunch: $35, Dinner: $75 or local market per-diem schedule).
   - Require business purpose and full names/titles of all attendees for business entertainment expenses.
3. **Restricted & Ineligible Categories:**
   - Flag non-reimbursable expenditures: Personal grooming, in-flight Wi-Fi (if not business-essential), hotel pay-per-view movies, traffic/parking citations, alcohol purchased without business dining accompaniment.
   - Scrutinize weekend purchases (Saturday/Sunday) unless associated with documented business travel itineraries.
4. **Flight & Accommodation Rules:**
   - Flights under 6 hours must be booked in Economy / Coach. Flag unauthorized Business/First class bookings.
   - Hotel room rates exceeding designated city caps require documented director pre-approval.

## Output Schedule
Deliver an Expense Audit Summary listing: Employee Name, Claim ID, Date, Amount, Category, Breach Type, Status (Approved / Pending Receipts / Rejected / Escalated), and Employee Communication Note.`
  },
  {
    agentName: "Purchase Commitment Tracker",
    label: "Open Purchase Commitment & Exposure Tracking",
    description: "Use when computing open purchase order commitments, analyzing un-invoiced balances, and determining future cash outflow requirements by department.",
    instructions: `## Purpose & Scope
Governs the monitoring of legally binding procurement commitments and open purchase orders (POs) to ensure budgetary control and accurate cash forecasting.

## Calculation Mechanics
1. **Open PO Obligation:**
   \`Open Commitment = (PO Ordered Quantity * PO Unit Price) - Invoiced Quantity Amount\`
   - Subtract any line items formally cancelled, closed, or de-obligated by procurement.
2. **Aged & Stale Commitment Identification:**
   - Category A (Current Active): Promised delivery date is within the next 60 days.
   - Category B (Aged / Overdue Delivery): Promised delivery date has passed but PO remains open in ERP without corresponding GRN.
   - Category C (Dormant Commitment): No activity, delivery, or invoicing for >90 days past promised delivery date.
3. **De-obligation Recommendations:**
   - Review open commitments older than 180 days with department budget owners.
   - Where goods/services will not be delivered, initiate formal de-obligation entries to release committed capital back into operating budgets.

## Exposure Reporting
Tabulate open commitments by: Department / Cost Centre, Vendor Name, PO Number, Total PO Value, Invoiced-to-Date, Open Un-invoiced Exposure, and Expected Cash Outflow Timing (Month 1, Month 2, Month 3+).`
  },

  /* ── 3. Accounts Receivable & Working Capital ─────────────────── */
  {
    agentName: "Receivables Collection Chaser",
    label: "Accounts Receivable Dunning & Collections Communication",
    description: "Use when categorizing overdue customer balances by ageing bucket, drafting staged dunning notices, and formulating tailored collection strategies.",
    instructions: `## Purpose & Scope
Defines the systematic dunning and receivables collection strategy to accelerate cash collection while preserving positive customer business relationships.

## Dunning Stage Matrix
1. **Stage 1: Courtesy Reminder (1 to 10 Days Past Due)**
   - Tone: Friendly, cooperative, customer service oriented.
   - Action: Confirm receipt of original invoice; inquire whether customer requires copy invoice or statement; verify no billing dispute exists.
2. **Stage 2: Formal Dunning Notice (11 to 30 Days Past Due)**
   - Tone: Firm, direct, professional.
   - Action: State overdue invoice reference numbers, aggregate outstanding balance, and contracted payment terms. Request payment confirmation or payment date commitment within 5 business days.
3. **Stage 3: Urgent Final Notice & Credit Hold Warning (31 to 60 Days Past Due)**
   - Tone: Formal, serious, escalation-oriented.
   - Action: Notify customer that failure to settle will result in immediate suspension of credit line, order shipping hold, and potential transfer to external legal collections.
4. **Stage 4: Formal Demand & Legal Escalation (>60 Days Past Due)**
   - Action: Formal pre-legal demand letter. Immediate suspension of services. Evaluation for bad debt provision.

## Special Circumstances
- Active Disputes: If customer logged an unresolved billing dispute, pause dunning sequence on the disputed portion and route immediately to Sales/Billing Operations for resolution within 48 hours.
- Promises to Pay: Log explicit promise-to-pay date and amount. If missed, immediately advance by one dunning tier.`
  },
  {
    agentName: "Customer Credit Risk Screener",
    label: "B2B Customer Creditworthiness & Risk Assessment",
    description: "Use when evaluating new customer credit applications, interpreting commercial credit bureau scores, and determining initial credit terms.",
    instructions: `## Purpose & Scope
Provides credit risk assessment criteria for onboarding corporate customers and establishing appropriate credit exposure limits.

## Five Cs of Credit Assessment
1. **Character (Reputation & Track Record):**
   - Review commercial registry filings, litigation records, bankruptcy checks, and years in continuous operation (minimum 2 years preferred for unsecured terms).
2. **Capacity (Operating Cash Flow & Liquidity):**
   - Analyze latest financial statements: Quick Ratio (\`Cash + AR / Current Liabilities\` > 1.0), Debt-to-Equity Ratio, and Operating Margin trend.
3. **Capital (Financial Strength & Net Worth):**
   - Tangible Net Worth calculation. Verify capitalization adequacy relative to requested credit limit.
4. **Collateral & Guarantees:**
   - Determine whether parent company corporate guarantees, personal director guarantees, or Standby Letters of Credit (SBLC) are required.
5. **Conditions:**
   - Macroeconomic headwinds, industry sector stability, and geographic jurisdiction risk.

## Credit Rating Scoring Framework
- Score 80-100 (Low Risk): Standard terms approved (Net 30/Net 45) up to standard formula limit.
- Score 50-79 (Moderate Risk): Restricted terms (Net 15) or lower credit threshold with mandatory monthly review.
- Score <50 (High Risk): Advance payment required (PIA), Cash Against Documents, or irrevocable Letter of Credit (LC).`
  },
  {
    agentName: "Cash Application Matcher",
    label: "Remittance Advice & Cash Application Matching",
    description: "Use when matching unapplied bank receipts against customer open invoices, interpreting partial remittances, and handling short payments.",
    instructions: `## Purpose & Scope
Sets the operational methodology for applying incoming customer bank payments to accounts receivable ledgers with precision and audit traceability.

## Matching Hierarchy
1. **Tier 1: Deterministic Match:**
   - Exact match on Customer Account Number + Invoice Number referenced in bank wire memo + Amount matches open invoice exactly.
2. **Tier 2: Remittance Advice Extraction:**
   - Parse electronic or PDF remittance advice. Match multiple invoices against a single lumped wire transfer.
   - Ensure \`Sum(Invoices Listed) - Disallowed Deductions == Net Bank Receipt\`.
3. **Tier 3: Customer + Amount Match:**
   - Customer identified via bank ordering account name/IBAN, and receipt amount equals the sum of one or more open items in customer's subledger.
4. **Tier 4: Partial Payments & Short Payments:**
   - Apply payment as partial payment against the oldest open invoice unless remittance advice specifies specific invoices.
   - Never write off residual differences automatically.

## Dispute & Deduction Handling
- Identify unauthorized deductions: Cash discounts taken after discount expiration, unapproved debit memos, freight chargebacks.
- Open an AR Dispute Record for any deduction > $50.00, tag with appropriate reason code, and notify the credit controller for customer follow-up.`
  },
  {
    agentName: "DSO Driver Analyst",
    label: "Days Sales Outstanding (DSO) Decomposition",
    description: "Use when calculating Days Sales Outstanding (DSO), isolating collection vs billing volume impacts, and identifying key customer delinquency drivers.",
    instructions: `## Purpose & Scope
Governs the mathematical calculation and operational decomposition of Days Sales Outstanding (DSO) across business units and customer segments.

## Calculation Methodologies
1. **Standard DSO:**
   \`DSO = (Total Accounts Receivable / Total Credit Sales in Period) * Number of Days in Period\`
2. **Countback (Exhaustion) Method (Preferred for accuracy):**
   - Step 1: Take period-ending AR.
   - Step 2: Subtract current month's gross credit sales. If AR > Sales, add 30/31 days and carry remaining AR to prior month.
   - Step 3: Repeat subtraction until AR balance is exhausted.
   - Step 4: Sum fractional days. (Eliminates seasonal sales distortion inherent in standard DSO).
3. **Best Possible DSO (BPDSO):**
   \`BPDSO = (Current / Not-Yet-Due AR / Total Credit Sales) * Days in Period\`
   - Measures theoretical DSO if all customers paid strictly on contractual terms.
4. **Collection Effectiveness Index (CEI):**
   \`CEI = ((Beginning AR + Credit Sales - Ending Total AR) / (Beginning AR + Credit Sales - Ending Current AR)) * 100\`

## Root-Cause Decomposition
- Decompose month-on-month DSO variance into:
  - *Sales Volume Impact:* Growth or decline in underlying gross revenues.
  - *Terms Shift:* Contractual extension of terms granted to key accounts.
  - *Collection Degradation:* Operational slip in collections, disputes, or customer payment delays.
- Highlight top 10 delinquent accounts driving >50% of the overdue DSO balance.`
  },
  {
    agentName: "Credit Limit Review Board",
    label: "Credit Limit Recalibration & Exposure Review",
    description: "Use when performing periodic reviews of customer credit limits, comparing credit usage to payment behaviour, and recommending adjustments.",
    instructions: `## Purpose & Scope
Provides structured criteria for annual and event-driven reviews of customer credit facilities to maximize sales while managing default probability.

## Review Triggers
- Annual scheduled review for top 20% accounts by turnover.
- Utilization breach: Customer consistently operating at >90% of credit limit.
- Payment deterioration: Customer average days to pay exceeds agreed terms by >15 days for two consecutive quarters.
- External warning: Material drop in credit rating agency score or adverse public news.

## Recalibration Formula
\`Recommended Limit = (Projected Monthly Revenue * (Contracted Days + Historical Payment Delay Days) / 30) * Peak Season Buffer (1.15 to 1.25)\`

## Governance & Approval Thresholds
- Limit Reductions: Can be enacted immediately by Credit Manager upon negative covenant breach or persistent delinquency.
- Limit Increases:
  - Up to $50,000: Credit Controller sign-off.
  - $50,001 - $250,000: Head of Credit / Corporate Controller approval.
  - >$250,000: CFO / Treasury Committee approval.

## Recommendation Format
Deliver an assessment showing: Customer Legal Name, Current Limit, Requested/Recommended Limit, Historical 12-Month Spend, Payment Track Record (DSO/Overdue %), Rationale, and Approved Signatures.`
  },
  {
    agentName: "Billing Leakage Detector",
    label: "Unbilled Revenue & Billing Leakage Detection",
    description: "Use when reconciling completed service delivery milestones, timesheets, or shipments against billing registers to detect unbilled revenue.",
    instructions: `## Purpose & Scope
Establishes the reconciliation framework between operational delivery data and financial billing ledgers to recover unbilled revenue and prevent revenue leakage.

## Leakage Audit Vectors
1. **Shipment vs Billing (Goods):**
   - Match inventory goods issue (bill of lading, courier tracking delivery) against generated sales invoices.
   - Flag shipments older than 3 business days that have no corresponding invoice in the sales ledger.
2. **Milestone / Contract Invoicing (Projects & Services):**
   - Compare active client contracts and project management milestone completions against billing schedules.
   - Screen for achieved milestones where invoicing was not initiated by the project manager.
3. **Usage & Metered Billing (SaaS / Subscriptions):**
   - Extract raw API / metered consumption logs from production databases.
   - Compare consumption against tier limits and overage billing registers.
   - Detect customer accounts where overage was logged but invoice charge equaled base subscription rate.
4. **Contractual Price Escalation Audits:**
   - Verify that agreed annual price escalations (e.g. CPI + 2%) were activated on contract anniversary dates.

## Quantification & Recovery Dossier
Generate a Billing Leakage Schedule detailing: Customer ID, Contract Reference, Nature of Unbilled Delivery, Delivery Date, Unbilled Amount, Responsible Account Manager, and Immediate Invoicing Action.`
  },

  /* ── 4. Treasury & Cash Management ────────────────────────────── */
  {
    agentName: "Thirteen-Week Cash Flow Forecaster",
    label: "Direct Method 13-Week Cash Flow Forecasting",
    description: "Use when constructing rolling 13-week short-term cash flow models using direct cash receipts, scheduled disbursements, and minimum liquidity buffers.",
    instructions: `## Purpose & Scope
Provides operational guidelines for building, updating, and stress-testing a rolling 13-week direct cash flow forecast to safeguard corporate solvency and liquidity.

## Modeling Structure & Horizon
- **Horizon:** 13 weekly buckets starting on Monday of the current week.
- **Methodology:** Direct cash receipts and disbursements method (Cash Inflows - Cash Outflows = Net Operating Cash Flow).

## Cash Inflow Estimation Rules
- **Weeks 1 to 2:** High certainty. Open AR invoices scheduled by customer historical payment pattern (actual DSO adjustment, not nominal invoice due date).
- **Weeks 3 to 4:** Invoices expected from current billing runs adjusted for collection velocity factor (e.g. 85%).
- **Weeks 5 to 13:** Projected sales forecasts converted to cash collections using lagged distribution curve (e.g. 40% Month 1, 50% Month 2, 8% Month 3, 2% Bad Debt).

## Cash Outflow Scheduling Rules
- **Non-Negotiable Fixed Outflows:** Payroll and associated employer taxes (precise payroll calendar dates), Debt service (interest + principal amortization), Facility rent/leases.
- **Supplier AP Outflows:** Group by payment run schedule. Distinguish between critical operational suppliers and discretionary vendors.
- **Tax Outflows:** Scheduled VAT/GST, quarterly corporate tax instalments, property taxes.

## Liquidity Buffer & Thresholds
- Calculate Net Ending Cash Balance per week.
- Test against Board-mandated Minimum Operating Cash Buffer.
- If forecast indicates cash dip below buffer within 6 weeks, trigger immediate treasury liquidity mitigation protocol.`
  },
  {
    agentName: "Bank Statement Reconciler",
    label: "Bank to Cash Ledger Reconciliation Procedure",
    description: "Use when reconciling raw electronic bank statements with general ledger cash accounts, identifying unpresented cheques, or clearing bank fees.",
    instructions: `## Purpose & Scope
Defines standard operating procedure for reconciling bank account statements against internal cash ledger accounts across all operating and treasury accounts.

## Core Reconciliation Steps
1. **Balance Alignment Verification:**
   - Verify: \`Opening Bank Statement Balance == Prior Month Closing Bank Statement Balance\`.
   - Verify: \`GL Cash Opening Balance == Prior Month Reconciled Book Balance\`.
2. **Transaction Clearing Match:**
   - Match bank statement credits (deposits) against GL cash receipts.
   - Match bank statement debits (withdrawals/wires) against GL disbursement entries.
   - Clear matching pairs: Same amount, matching transaction reference / cheque number, within date tolerance (+/- 3 days).
3. **Identification of Reconciling Line Items:**
   - **Deposits in Transit:** Cash receipts entered into the accounting system on or before cut-off date but not yet credited on the bank statement.
   - **Outstanding / Unpresented Cheques:** Cheques issued and booked into AP ledger that have not been presented to the bank for payment.
   - **Bank-Originated Charges & Credits:** Bank service charges, merchant processing fees, interest earned, foreign exchange fees recorded on bank statement but not yet entered into GL.

## Mathematical Proof
\`Bank Statement Ending Balance + Deposits in Transit - Outstanding Cheques +/- Bank Errors = Reconciled Bank Balance\`
\`GL Book Ending Balance + Interest Earned - Bank Fees +/- Book Errors = Reconciled Book Balance\`
*Condition:* Reconciled Bank Balance must equal Reconciled Book Balance exactly.`
  },
  {
    agentName: "FX Exposure Snapshot",
    label: "Multi-Currency Exposure & FX Sensitivity Analysis",
    description: "Use when consolidating multi-currency balance sheet positions, revaluing monetary balances at spot rates, and assessing FX volatility risk.",
    instructions: `## Purpose & Scope
Standardizes the tracking, revaluation, and risk assessment of multi-currency financial exposures to protect earnings from foreign exchange volatility.

## Exposure Classification
1. **Transaction Exposure (Balance Sheet Monetary Items):**
   - Monetary Assets: Foreign currency bank accounts, foreign currency customer receivables, intercompany loans.
   - Monetary Liabilities: Foreign currency vendor payables, debt facilities denominated in non-base currency.
   - Net Monetary Exposure = \`Foreign Assets - Foreign Liabilities\` per currency.
2. **Revaluation Standard (IAS 21 / ASC 830):**
   - Mark all open foreign monetary balances to market using the official period-end closing spot rate.
   - Calculate unrealized foreign exchange gain/loss:
     \`Unrealized Gain/Loss = Balance in Foreign Currency * (Closing Spot Rate - Original Booking Rate)\`.
   - Post to P&L (or OCI if qualifying net investment hedge).

## Sensitivity Analysis & Stress Testing
- Run stress test scenarios on all net exposures:
  - Base Case (Current closing spot rates).
  - +/- 5% FX rate shift.
  - +/- 10% FX rate shift.
  - Worst-case historical 30-day volatility scenario.
- Report dollar sensitivity impact on quarterly operating income and EBITDA.`
  },
  {
    agentName: "Debt Covenant Monitor",
    label: "Financial Debt Covenant Compliance & Headroom Analysis",
    description: "Use when calculating credit facility covenant ratios (Leverage, Interest Cover, Fixed Charge), evaluating headroom, and projecting compliance.",
    instructions: `## Purpose & Scope
Establishes the calculation standards and monitoring routine for debt covenants to ensure compliance with bank credit agreements, indentures, and private placements.

## Standard Covenant Formulas
1. **Consolidated Net Leverage Ratio:**
   \`Net Debt / LTM EBITDA\`
   - *Net Debt:* Total Gross Borrowings (drawn facilities + term loans + notes + finance leases) - Unrestricted Cash.
   - *EBITDA:* Adjusted in strict compliance with credit agreement definitions (e.g. adding back permitted non-recurring restructuring expenses up to contract cap).
2. **Interest Coverage Ratio:**
   \`LTM EBITDA / Consolidated Cash Interest Expense\`
   - Ensure interest expense reflects actual cash interest paid, excluding non-cash PIK interest or debt issue cost amortization if allowed by agreement.
3. **Fixed Charge Coverage Ratio (FCCR):**
   \`(EBITDA - Unfunded Capex - Cash Taxes) / (Debt Service Principal + Cash Interest)\`

## Headroom & Warning Framework
- **Covenant Headroom Calculation:**
  \`Headroom = Contractual Covenant Limit - Actual Calculated Metric\`
- **Early Warning Status:**
  - *Green:* Headroom > 20% of contractual limit.
  - *Amber:* Headroom between 10% and 20%. Trigger treasury alert and sensitivity reforecast.
  - *Red:* Headroom < 10% or projected breach within next two rolling quarters. Escalate to CFO immediately.`
  },
  {
    agentName: "Idle Cash Sweep Advisor",
    label: "Treasury Liquidity Buffer & Cash Sweep Optimisation",
    description: "Use when evaluating operating account balances against required liquidity buffers, calculating sweepable surplus, and optimizing short-term yield.",
    instructions: `## Purpose & Scope
Provides decision-making criteria for daily and weekly cash sweeps, pooling surplus liquidity from decentralized operating accounts to maximize interest yield.

## Buffer Sizing Methodology
1. **Target Operating Buffer:**
   - Establish minimum buffer per operating account:
     \`Operating Buffer = Peak Single-Day Disbursement in Last 90 Days * 1.5 Safety Margin\`
   - Factor in weekly payroll runs and scheduled automated tax debits.
2. **Sweepable Surplus Calculation:**
   \`Sweepable Cash = Current Ledger Available Balance - Operating Buffer - Float In-Transit\`
   - If Sweepable Cash > $50,000 (or bank transfer cost efficiency threshold), recommend immediate sweep.

## Yield Placement Guidelines
- Evaluate sweep instruments based on liquidity access rules:
  - **Tier 1 (Instant Access / Overnight):** Overnight interest-bearing deposit accounts, automated zero-balance sweep accounts (ZBA).
  - **Tier 2 (7 to 30-Day Notice):** Money Market Funds (AAA rated, government securities backed), short-term Treasury bills.
- Calculate annualized incremental interest gain:
  \`Incremental Yield = Sweepable Amount * (Investment Rate - Operating Account Rate) * (Days / 365)\`.`
  },
  {
    agentName: "Payment Run Approver Brief",
    label: "AP Disbursement Run Exception & Control Summary",
    description: "Use when summarizing proposed batch payment runs for executive approval, highlighting payment anomalies, high-value wires, and new beneficiary banks.",
    instructions: `## Purpose & Scope
Defines the executive control brief and risk screening required prior to the release and authorization of accounts payable payment batches.

## Critical Verification Controls
1. **Batch Integrity:**
   - Total Batch Value, Currency Breakdown, Total Number of Payments.
   - Verify payment run total does not exceed authorized approver authority limit.
2. **Exception Screening Tiers:**
   - **High-Value Threshold:** Individual payments exceeding $25,000 (or internal executive threshold) must be itemized with PO reference and business justification.
   - **New Beneficiary / Bank Change Alert:** Flag any vendor in the payment batch whose bank account details were created or modified within the last 30 days. Require dual-control verification check.
   - **Manual Override / Urgent Payment:** Flag any invoice forced into the payment run outside normal payment term schedules.
   - **Cross-Border / High-Risk Jurisdiction Payments:** Highlight payments sent to foreign bank accounts or entities subject to sanctions/AML review.

## Executive Brief Deliverable
Present a one-page approval briefing: Batch ID, Bank Account to Debit, Total Run Amount, Number of Beneficiaries, Count of Exceptions, Table of Top 5 Largest Payments, Table of Bank Account Changes, and Sign-off Box.`
  },

  /* ── 5. Financial Planning & Analysis (FP&A) ──────────────────── */
  {
    agentName: "Budget versus Actual Narrator",
    label: "Budget vs Actual Performance Reporting",
    description: "Use when analyzing departmental budget variances, isolating run-rate discrepancies, and preparing executive commentary on performance targets.",
    instructions: `## Purpose & Scope
Standardizes the analysis of budget versus actual financial results across departments and business units, focusing management attention on underlying drivers.

## Variance Hierarchy & Thresholds
- Screen all general ledger line items against approved budget baseline.
- **Reporting Thresholds:**
  - Level 1: Variance > $10,000 and > 10% vs budget -> Full commentary required.
  - Level 2: Variance > $50,000 regardless of percentage -> Detailed operational decomposition required.

## Analysis Categorization
Classify every material variance into one of four operational categories:
1. **Volume/Activity Driver:** Caused by changes in customer transaction count, client count, or production volume.
2. **Unit Cost/Rate Variance:** Caused by vendor price increases, wage inflation, or unbudgeted premium rates.
3. **Timing / Phase Shift:** Expense or revenue scheduled for this month occurred earlier or will occur later.
4. **Permanent Savings or Overrun:** Structural shift that will permanently impact the full-year outturn.

## Commentary Formatting Standard
For each variance group:
- State the Dollar and Percentage variance clearly.
- State whether the variance is Favourable (F) or Unfavourable (U) to bottom-line EBITDA.
- Provide a two-sentence operational explanation stating what happened and what the full-year forecast impact will be.`
  },
  {
    agentName: "Rolling Forecast Assembler",
    label: "Rolling Financial Forecast Consolidation",
    description: "Use when rolling actual monthly results into multi-quarter financial forecasts, adjusting remaining baseline assumptions, and tracking guidance.",
    instructions: `## Purpose & Scope
Guides the monthly rolling forecast cadence, integrating completed actual accounting periods with dynamic forward projections.

## Rolling Process Steps
1. **Actualization:**
   - Replace the prior forecast period with finalized general ledger actuals.
   - Calculate the actual-to-prior-forecast variance to establish the exit run-rate.
2. **Horizon Extension:**
   - Maintain a continuous rolling horizon of at least 4 to 6 quarters forward.
   - Add the newest outer quarter using validated growth drivers and seasonality indices.
3. **Run-Rate Adjustment:**
   - Assess whether variances in the closed period represent temporary timing or permanent run-rate changes.
   - Adjust baseline revenues and operating expenditures for subsequent periods accordingly.
4. **Working Capital & Balance Sheet Integration:**
   - Re-derive AR, AP, and Inventory projections dynamically based on updated forward revenue and COGS assumptions.

## Deliverable Format
Provide a 5-quarter financial bridge comparing: Previous Forecast vs Current Rolling Forecast vs Approved Budget, with waterfall explanation of major forecast revisions.`
  },
  {
    agentName: "Headcount Cost Modeller",
    label: "Fully Burdened Headcount & Compensation Costing",
    description: "Use when calculating fully loaded employee personnel costs, phasing new hires, and modeling payroll taxes, benefits, and bonus accruals.",
    instructions: `## Purpose & Scope
Governs the financial modeling and budgeting of compensation, payroll taxes, benefits, and variable incentive costs for existing workforce and planned hires.

## Cost Breakdown Components
1. **Base Salary & Wages:**
   - Phased by exact hiring start date (e.g. Mid-month start = 50% monthly salary).
2. **Statutory Employer Payroll Taxes:**
   - Federal/State Unemployment, Employer FICA/Medicare, National Insurance, or local equivalent statutory contributions.
   - Apply statutory salary caps where applicable (e.g. Social Security wage base limits).
3. **Fringe Benefits & Healthcare:**
   - Corporate healthcare, dental, life assurance, retirement plan matching (401k/pension).
   - Use either exact tier elections or departmental standard fringe burden percentage (e.g. 18% to 24% of base salary).
4. **Variable Compensation & Bonus Accruals:**
   - Model annualized bonus target percentage accrued evenly across service months.
   - Commission plans tied directly to phased revenue ramp curves.

## Modeling Deliverable
Generate a detailed Headcount Cost Schedule: Department, Role Title, Target Hire Date, Base Salary, Employer Taxes, Benefits Burden, Incentive Accrual, and Total Fully Burdened Cost by Month.`
  },
  {
    agentName: "Unit Economics Calculator",
    label: "Unit Economics & Contribution Margin Modelling",
    description: "Use when calculating Customer Acquisition Cost (CAC), Customer Lifetime Value (LTV), payback period, and contribution margin per unit.",
    instructions: `## Purpose & Scope
Provides standard analytical definitions and calculation formulas for evaluating unit economics, gross margins, and customer-level financial profitability.

## Core Financial Metrics & Formulas
1. **Contribution Margin 1 & 2:**
   - \`Gross Margin = (Revenue - Direct COGS) / Revenue\`
   - \`Contribution Margin = (Revenue - Direct COGS - Variable Sales & Support Costs) / Revenue\`
2. **Customer Acquisition Cost (CAC):**
   \`CAC = Total Fully Loaded Sales & Marketing Expenses in Period / Number of New Customers Acquired\`
   - Include sales team salaries, marketing spend, commissions, and travel expenses.
3. **Customer Lifetime Value (LTV):**
   \`LTV = (Average Revenue Per User (ARPU) * Gross Margin %) / Churn Rate\`
4. **LTV to CAC Ratio & CAC Payback:**
   - \`LTV:CAC Ratio = LTV / CAC\` (Target benchmark: >= 3.0x).
   - \`CAC Payback (Months) = CAC / (Average Monthly Revenue per Customer * Gross Margin %)\` (Target benchmark: < 12 to 18 months).

## Reporting Breakdown
Tabulate unit metrics by customer cohort, product line, and distribution channel, identifying sub-economic segments requiring pricing or go-to-market adjustments.`
  },
  {
    agentName: "Scenario Sensitivity Runner",
    label: "Multi-Scenario Financial Sensitivity Analysis",
    description: "Use when stress-testing financial models across base, upside, and downside assumptions, isolating key driver elasticity and liquidity impact.",
    instructions: `## Purpose & Scope
Defines the methodology for financial stress testing and scenario modeling to evaluate business resilience against market shocks and operational disruptions.

## Standard Scenario Architecture
1. **Base Case:** Management's central operating plan reflecting current run-rates and realistic pipeline conversion.
2. **Upside Case (+15% to +25% Growth):** Accelerated customer adoption, lower churn, successful price increases. Focus on capacity constraints and capital requirements.
3. **Downside / Stress Case (-15% to -30% Revenue):** Severe macro downturn, key customer loss, price compression, extended debtor payment delays (+20 days DSO).

## Driver Elasticity Evaluation
- Calculate sensitivity coefficient for primary financial drivers:
  - 1% decrease in gross pricing.
  - 10% increase in critical raw material / hosting COGS.
  - 2-month delay in new product release.
- Map the resulting impact on EBITDA, ending cash balance, and debt covenant headroom.

## Scenario Dashboard
Present a comparative matrix: Base vs Upside vs Downside across Revenue, Gross Margin %, EBITDA, Free Cash Flow, Minimum Cash Balance, and Required Mitigation Levers.`
  },
  {
    agentName: "Board KPI Pack Builder",
    label: "Executive KPI & Board Pack Construction",
    description: "Use when aggregating strategic executive metrics, historical trends, and balance sheet KPIs into a cohesive monthly board presentation pack.",
    instructions: `## Purpose & Scope
Governs the assembly, validation, and design standards of monthly and quarterly executive financial management packs for the Board of Directors.

## Standard Pack Structure
1. **Executive Summary Dashboard:**
   - Key Scorecard: Revenue, ARR/MRR (if recurring), Gross Margin %, Adjusted EBITDA, Free Cash Flow, Ending Cash, Headcount.
   - Traffic light indicator (Red/Amber/Green) against board-approved budget targets.
2. **Financial Performance Section:**
   - Summary Income Statement with prior year and budget comparisons.
   - Revenue walk and bridge commentary.
   - Operating expense breakdown by function (R&D, S&M, G&A).
3. **Working Capital & Treasury Health:**
   - Cash bridge (walk from Operating Cash Flow to Net Change in Cash).
   - Aging of receivables and DSO trend.
   - Capital expenditure against approved plan.
4. **Non-Financial Operational Indicators:**
   - Customer retention / net dollar retention (NDR), employee turnover, pipeline coverage ratio.

## Validation & Review Checklist
- Every metric must reconcile back to signed-off general ledger figures or verified operational data stores.
- Text commentary must focus strictly on strategic implications, competitive context, and forward projections rather than restating numbers.`
  },
  {
    agentName: "Departmental Spend Benchmarker",
    label: "Indirect Spend Benchmarking & Category Analysis",
    description: "Use when analyzing indirect operating expenses by department, benchmarking spend against industry averages, and identifying cost containment targets.",
    instructions: `## Purpose & Scope
Provides analytical frameworks for benchmarking indirect operating expenditures across corporate departments and against peer industry benchmarks.

## Spend Category Taxonomies
1. **Information Technology & Software:** SaaS software licenses per employee, cloud hosting per customer, hardware depreciation.
2. **Professional & Legal Fees:** External legal counsel, accounting/audit fees, tax compliance, management consulting.
3. **Marketing & Travel:** Customer acquisition marketing, events, internal travel, client entertainment.
4. **Facilities & Workplace:** Rent per square foot, utilities, office supplies, meal subsidies.

## Benchmark Analysis Metrics
- Measure intensity ratios:
  - Spend as % of Total Corporate Revenue.
  - Spend per Full-Time Equivalent (FTE) Employee.
  - Spend per Department Headcount.
- Compare metrics against industry peer quartiles (Top Quartile / Median / Bottom Quartile).

## Action Plan Formulation
Highlight category spend lines exceeding median benchmarks by >25%, identify redundant tooling/vendors across departments, and draft cost consolidation recommendations.`
  },
  {
    agentName: "Capex Business Case Evaluator",
    label: "Capital Investment Appraisal (NPV/IRR/Payback)",
    description: "Use when evaluating capital expenditure requests, discounting cash flows, calculating NPV and IRR, and assessing hurdle rate compliance.",
    instructions: `## Purpose & Scope
Establishes the corporate financial methodology for appraising proposed capital investments (Capex), asset acquisitions, and major technology projects.

## Financial Appraisal Formulas
1. **Net Present Value (NPV):**
   \`NPV = Sum(Cash Flow_t / (1 + WACC)^t) - Initial Investment\`
   - Discount cash flows using corporate Weighted Average Cost of Capital (WACC) or project-specific hurdle rate.
   - Decision Rule: Project is economically viable if NPV > 0.
2. **Internal Rate of Return (IRR):**
   - Discount rate that equates NPV to zero: \`NPV = 0\`.
   - Decision Rule: Accept project if \`IRR > Required Corporate Hurdle Rate\`.
3. **Discounted Payback Period:**
   - Number of years required for cumulative discounted cash inflows to fully recover initial cash outlay. (Target: < 3 years).
4. **Profitability Index (PI):**
   \`PI = Present Value of Future Cash Inflows / Initial Outlay\`.

## Risk & Governance Review
- Challenge baseline assumptions: Revenue growth claims, operational savings estimates, implementation contingency buffer (minimum 15% Capex contingency required).
- Produce a Capital Allocation Memorandum summarizing NPV, IRR, Payback, Critical Risks, and Post-Implementation Review Milestones.`
  },

  /* ── 6. Tax & Regulatory Compliance ───────────────────────────── */
  {
    agentName: "Indirect Tax Return Preparer",
    label: "Sales Tax and VAT Return Preparation Standard",
    description: "Use when compiling taxable sales, input tax credits, and exempt supplies for indirect tax returns, and reconciling tax liability to GL.",
    instructions: `## Purpose & Scope
Standardizes the compilation, reconciliation, and audit verification of indirect tax returns (VAT, GST, State Sales & Use Tax).

## Reconciliation Sequence
1. **Output Tax (Sales Tax Collected):**
   - Reconcile sales ledger taxable revenue against gross indirect tax collected by jurisdiction:
     \`Gross Taxable Sales * Statutory Rate == Tax Collected\`
   - Review tax-exempt transactions to ensure valid resale certificates or exemption documentation are on file.
2. **Input Tax (VAT/GST Paid on Purchases):**
   - Reconcile AP input tax account with valid tax invoices from suppliers.
   - Verify that all claims have a valid VAT/GST registration number and meet local recovery rules (e.g., restricted recovery on entertainment or passenger vehicles).
3. **General Ledger to Tax Return Reconciliation:**
   - \`GL Sales Tax Payable Account Balance == Net Tax Due on Return (Output Tax - Deductible Input Tax)\`.
   - Any difference between the return calculation and the balance sheet tax liability must be investigated and resolved prior to filing.

## Exception Flags
- Flag zero-rated or exempt sales lacking customer tax registration records.
- Flag transactions with non-standard tax rates or inverted jurisdictions.`
  },
  {
    agentName: "Tax Law Change Watcher",
    label: "Statutory & Regulatory Tax Change Assessment",
    description: "Use when evaluating new statutory tax enactments, assessing nexus changes, rate revisions, or changes to corporate tax deduction rules.",
    instructions: `## Purpose & Scope
Provides guidelines for monitoring, interpreting, and assessing operational impacts of statutory tax changes across operating jurisdictions.

## Assessment Dimensions
1. **Nexus & Filing Obligations:**
   - Evaluate economic nexus thresholds for remote sales (e.g. Wayfair state-specific dollar and transaction volume thresholds).
   - Identify new corporate income tax, digital services tax, or gross receipts tax triggers.
2. **Rate & Bracket Adjustments:**
   - Log changes in corporate statutory rates, indirect tax rates, and payroll tax caps.
   - Schedule configuration changes in ERP tax calculation engines ahead of statutory effective dates.
3. **Deductibility & Incentive Alterations:**
   - Track restrictions on interest expense deductibility (e.g. Section 163(j) limitations).
   - Evaluate new research & development (R&D) tax credit rules, capital depreciation allowances (bonus depreciation phase-outs), or environmental incentives.

## Action Memo
Produce a Tax Regulatory Impact Brief: Jurisdiction, Enacted Legislation, Effective Date, Financial Statement Impact (Current and Deferred Tax), ERP Configuration Required, and Compliance Deadlines.`
  },
  {
    agentName: "Transfer Pricing File Drafter",
    label: "OECD Transfer Pricing Local File Documentation",
    description: "Use when drafting transfer pricing local file documentation, analyzing intercompany transaction methodologies, and verifying arm's length compliance.",
    instructions: `## Purpose & Scope
Guides the authoring of Transfer Pricing documentation in full alignment with OECD Base Erosion and Profit Shifting (BEPS) Action 13 standards.

## Required Local File Structure
1. **Local Entity Description:**
   - Management structure, organizational chart, local business strategy, and competitive positioning.
2. **Intercompany Controlled Transactions:**
   - Comprehensive inventory of intercompany transactions: Management services, IP licensing, intercompany sales of goods, financing facilities.
   - State transaction volumes, contracting entity counterparties, and actual pricing applied.
3. **Functional Analysis (FAR):**
   - **Functions Performed:** Design, manufacturing, marketing, distribution, corporate oversight.
   - **Assets Employed:** Tangible assets, proprietary IP, customer databases, working capital.
   - **Risks Assumed:** Market risk, inventory obsolescence, credit risk, foreign exchange risk.
4. **Transfer Pricing Method Selection:**
   - Document selection of the most appropriate method: Comparable Uncontrolled Price (CUP), Resale Price, Cost Plus, or Transactional Net Margin Method (TNMM).
   - Document benchmark search criteria, database used, and established arm's length interquartile range.`
  },
  {
    agentName: "Withholding Tax Rate Look-up",
    label: "Cross-Border Double Tax Treaty Withholding Analysis",
    description: "Use when determining statutory and treaty withholding tax rates for cross-border dividend, interest, royalty, or service fee payments.",
    instructions: `## Purpose & Scope
Standardizes the determination and documentation of cross-border withholding tax (WHT) obligations under domestic law and bilateral Double Taxation Treaties (DTT).

## Analysis Workflow
1. **Transaction Characterization:**
   - Accurately categorize the cross-border payment: Dividends, Interest, Royalties (Software/IP license), Management Service Fees, Technical Service Fees.
2. **Domestic Statutory Rate Determination:**
   - Identify the source country's domestic statutory withholding tax rate applicable in the absence of a treaty.
3. **Treaty Rate & Eligibility Analysis:**
   - Identify applicable bilateral treaty between payor jurisdiction and payee jurisdiction.
   - **Beneficial Ownership Test:** Confirm recipient entity is the true beneficial owner of the income and not an artificial conduit entity.
   - **Limitation on Benefits (LOB) / Principal Purpose Test (PPT):** Verify recipient entity qualifies for treaty benefits under applicable anti-treaty shopping rules.
4. **Withholding Certificate & Form Requirements:**
   - Specify required formal tax documentation (e.g. IRS Form W-8BEN-E, local Tax Residency Certificate) that must be received prior to executing gross payment.`
  },

  /* ── 7. Technical Accounting & Governance ─────────────────────── */
  {
    agentName: "Accounting Standards Update Monitor",
    label: "GAAP & IFRS Technical Accounting Change Analysis",
    description: "Use when analyzing newly issued FASB Accounting Standards Updates (ASUs) and IASB standards for accounting policy and disclosure impact.",
    instructions: `## Purpose & Scope
Provides technical accounting frameworks for evaluating newly issued accounting standards and interpreting their balance sheet, P&L, and disclosure ramifications.

## Evaluation Process
1. **Standard Scoping:**
   - Review standard pronouncements from FASB (US GAAP) and IASB (IFRS).
   - Determine applicability based on company operations, contract structures, and industry sector.
2. **Gap Analysis & Transition Assessment:**
   - Compare existing corporate accounting policy against newly mandated recognition, measurement, or presentation criteria.
   - Evaluate available transition methods: Full Retrospective vs Modified Retrospective (cumulative effect adjustment to opening retained earnings).
3. **Operational & System Dependencies:**
   - Identify data capture gaps in current ERP and subledgers required to satisfy new reporting standards.
   - Design internal controls and validation routines over new accounting calculation engines.

## Deliverable
Deliver a Technical Accounting Assessment Memo: Standard Reference, Executive Summary, Scope & Applicability, Quantified Financial Impact, Transition Method Recommendation, and Action Roadmap.`
  },
  {
    agentName: "Lease Schedule Builder",
    label: "IFRS 16 / ASC 842 Lease Liability & ROU Scheduling",
    description: "Use when calculating Right-of-Use (ROU) assets and lease liabilities under IFRS 16 / ASC 842, determining incremental borrowing rates, and scheduling amortisation.",
    instructions: `## Purpose & Scope
Governs the technical accounting and balance sheet scheduling for operating and finance leases under IFRS 16 and ASC 842.

## Key Measurement Components
1. **Lease Liability Initial Measurement:**
   - Present value of future lease payments discounted using the rate implicit in the lease, or the lessee's Incremental Borrowing Rate (IBR):
     \`Lease Liability = Sum(Lease Payment_t / (1 + IBR)^t)\`
   - Include fixed payments, in-substance fixed payments, and probable residual value guarantees.
2. **Right-of-Use (ROU) Asset Initial Measurement:**
   - \`ROU Asset = Initial Lease Liability + Initial Direct Costs + Prepaid Lease Payments - Lease Incentives Received + Estimated Restoration Costs\`.
3. **Subsequent Measurement & Accounting Entries:**
   - **Lease Liability Amortisation:** Reduced by cash lease payments, increased by periodic interest accretion:
     \`Interest Expense = Carrying Lease Liability * IBR\`
   - **ROU Asset Amortisation:** Straight-line depreciation over the shorter of lease term or underlying asset economic life.

## Output Schedule
Generate a full monthly lease amortisation schedule: Period, Beginning Liability, Lease Cash Payment, Interest Expense, Principal Reduction, Ending Liability, ROU Depreciation Expense, and Ending ROU Asset Net Book Value.`
  },
  {
    agentName: "Revenue Recognition Assessor",
    label: "IFRS 15 / ASC 606 Five-Step Revenue Assessment",
    description: "Use when evaluating commercial customer contracts under the IFRS 15 / ASC 606 five-step model, identifying performance obligations, and allocating transaction price.",
    instructions: `## Purpose & Scope
Establishes the technical accounting procedure for evaluating customer contracts under the standardized Five-Step Revenue Model (IFRS 15 / ASC 606).

## The Five-Step Assessment Framework
1. **Step 1: Identify the Contract with a Customer:**
   - Confirm commercial substance, mutual approval, defined payment terms, and high probability of collection.
2. **Step 2: Identify Distinct Performance Obligations (POBs):**
   - Determine whether promised goods or services are capable of being distinct and distinct within the context of the contract.
   - Separate software licenses from implementation services, maintenance/updates (PCS), and cloud hosting.
3. **Step 3: Determine the Transaction Price:**
   - Calculate fixed consideration and estimate variable consideration (discounts, rebates, performance bonuses, refunds).
   - Apply the variable consideration constraint: Recognize variable revenue only to the extent that a significant reversal is highly improbable.
4. **Step 4: Allocate Transaction Price to POBs:**
   - Allocate relative Standalone Selling Prices (SSP) to each distinct performance obligation.
5. **Step 5: Recognize Revenue as/when POBs are Satisfied:**
   - Over time: Customer simultaneously receives and consumes benefits (e.g. SaaS subscriptions, recurring services).
   - Point in time: Control transfers at a specific date (e.g. perpetual software license key delivery, hardware delivery).`
  },
  {
    agentName: "Control Evidence Collector",
    label: "Internal Control Testing & Audit Sample Evaluation",
    description: "Use when designing audit sample populations, extracting control evidence, and testing internal controls over financial reporting (ICFR / SOX).",
    instructions: `## Purpose & Scope
Standardizes the extraction, sampling, and testing of audit evidence for Sarbanes-Oxley (SOX) compliance and internal control over financial reporting (ICFR).

## Audit Sampling Standards (AICPA Guidelines)
- Define complete population for the control frequency:
  - **Annual Control:** Sample size 1.
  - **Quarterly Control:** Sample size 2.
  - **Monthly Control:** Sample size 2 to 5.
  - **Weekly Control:** Sample size 5 to 10.
  - **Daily Control:** Sample size 25 to 40.
  - **Multiple Times Per Day / Automated:** Sample size 25 to 60.
- Ensure selection is randomized or stratified across all operating periods (avoid sampling exclusively from the final month).

## Evidence Verification Rules
1. **Evidence of Control Operation:**
   - Merely having an email saying 'approved' is insufficient. Evidence must demonstrate reviewer precision: Checkmark annotations, documented queries, recalculation notes, or formal workflow system approval audit trail with timestamp.
2. **Appropriate Segregation:**
   - Confirm preparer and reviewer are distinct individuals with appropriate delegation of authority limits.
3. **Completeness & Accuracy (IUC/IPE):**
   - Validate Information Used in the Control (IUC): Test parameters, query scripts, and filters used to generate underlying reports.

## Workpaper Summary
Document: Control Objective, Control Frequency, Population Size, Sample Selected, Evidence Reviewed, Exception Identified (Yes/No), Control Operating Effectiveness Conclusion.`
  },
  {
    agentName: "Segregation of Duties Conflict Detector",
    label: "Segregation of Duties (SoD) Conflict Matrix & Audit",
    description: "Use when auditing user access privileges in ERP systems to detect incompatible toxic access combinations and Segregation of Duties conflicts.",
    instructions: `## Purpose & Scope
Provides governance standards and conflict detection rules for monitoring Segregation of Duties (SoD) across financial systems to prevent fraud and unauthorized transactions.

## Classic Incompatible Role Pairs (Toxic Combinations)
1. **Vendor Master & Invoice Processing:**
   - Creating/modifying vendor records + Entering/approving vendor invoices. (Risk: Fictitious vendor payment fraud).
2. **Invoice Entry & Payment Release:**
   - Entering accounts payable invoices + Approving/executing bank payment runs. (Risk: Unauthorized disbursement).
3. **Journal Entry Preparation & Approval:**
   - Creating manual journal entries + Posting/approving journal entries without independent secondary review.
4. **Billing Creation & AR Write-Off:**
   - Generating customer invoices + Authorizing customer bad debt or credit note write-offs. (Risk: Concealment of intercepted cash).
5. **PO Creation & Goods Receipt:**
   - Creating purchase orders + Processing goods receipts. (Risk: Circumvention of three-way match).

## Audit & Analysis Protocol
- Run cross-system entitlement query comparing user roles and system privileges.
- Classify conflicts:
  - **Direct SoD Conflict:** Single user account holds both incompatible permissions.
  - **Actual Transaction Execution:** User not only held both permissions, but actually created AND approved transactions within the audit period.
- For each valid conflict, require immediate removal of one permission or establish documented, verified compensating controls.`
  },
  {
    agentName: "Fraud Red Flag Scanner",
    label: "Forensic Financial Transaction & Benford Screening",
    description: "Use when running forensic audit tests on transaction populations, applying Benford's Law, or identifying out-of-sequence payments.",
    instructions: `## Purpose & Scope
Establishes forensic testing procedures to detect occupational fraud, unauthorized transactions, asset misappropriation, and financial record tampering.

## Core Forensic Tests
1. **Benford's Law First-Digit Analysis:**
   - Compare leading digit distribution (1 through 9) of transaction populations against Benford's Law expected frequencies:
     - 1: 30.1%, 2: 17.6%, 3: 12.5%, 4: 9.7%, 5: 7.9%, 6: 6.7%, 7: 5.8%, 8: 5.1%, 9: 4.6%.
   - Flag significant positive deviations (Chi-Square test p < 0.05) on numbers 7, 8, or 9 as potential manipulation indicators.
2. **Threshold Avoidance (Just-Below Threshold):**
   - Screen for transactions clustered in the band 1% to 5% immediately below key approval limits (e.g. $4,900 to $4,999 vs $5,000 threshold).
3. **Sequential & Missing Invoice Number Analysis:**
   - Identify vendors whose invoice numbers are strictly sequential over extended periods (e.g. Invoice 101, 102, 103 received months apart), indicating the vendor may exist solely to bill this company.
4. **Keyword & Description Screening:**
   - Search transaction descriptions for high-risk strings: 'consulting', 'gift', 'facilitation', 'cash', 'reimbursement', 'special fee', 'urgent payment', 'retainer' without contract.

## Investigation Dossier
Output: Forensic Alert Summary, Transaction IDs, Suspect Attributes, Statistical Deviation Metric, and Investigative Next Steps.`
  },
  {
    agentName: "Audit Request Responder",
    label: "External Audit PBC Request Management & Review",
    description: "Use when managing Prepared by Client (PBC) auditor request lists, validating document completeness, and tracking audit deliverable deadlines.",
    instructions: `## Purpose & Scope
Provides operational standards for managing external auditor request lists (PBC - Prepared by Client), reviewing deliverable quality, and adhering to audit timetables.

## PBC Request Management Workflow
1. **Intake & Logging:**
   - Log each request in the central PBC tracker: Request ID, Audit Section (Cash, AP, Revenue, Equity), Auditor Owner, Internal Responsible Owner, Initial Due Date.
2. **Pre-Submission Quality & Completeness Review:**
   - Before releasing any document to external auditors, perform mandatory internal review:
     - **Mathematical Agreement:** Does the supporting schedule tie out exactly to the General Ledger and Trial Balance?
     - **Information Completeness:** Are all columns, dates, and references fully populated?
     - **Confidentiality / Privilege Check:** Does the document contain non-financial personal data, unredacted attorney-client privileged communications, or irrelevant sensitive IP? Redact appropriately.
3. **Version Control:**
   - Maintain immutable archive of all files transmitted to external auditors with transmission timestamp and recipient sign-off.
4. **Status & Bottleneck Escalation:**
   - Classify statuses: Open, In Progress, In Internal Review, Submitted, Auditor Accepted, Additional Inquiry Raised.
   - Escalate any PBC item overdue by >48 hours to Corporate Controller.`
  },
  {
    agentName: "Management Report Narrative Writer",
    label: "Executive Management Commentary Drafting",
    description: "Use when authoring executive commentary for monthly management packs, synthesizing operational performance, and articulating forward outlook.",
    instructions: `## Purpose & Scope
Governs the drafting and editorial standards for executive management reports, providing strategic context and actionable insights to senior leadership.

## Narrative Principles
- **Executive Conciseness:** Synthesize complex data into crisp, high-impact bullet points. Senior executives look for causes, implications, and remedies.
- **Tone:** Direct, confident, transparent, and forward-looking. Own misses honestly and present corrective actions immediately.
- **The 'What, Why, and So What' Framework:**
  - *What:* The exact numerical change (e.g. 'Operating expenses rose $120k (+8%) month-on-month').
  - *Why:* The commercial/operational root cause (e.g. 'Driven by $85k in unbudgeted external legal fees for patent litigation and $35k in expedited freight charges').
  - *So What:* The strategic or forward impact (e.g. 'Full-year EBITDA will absorb the legal fees; freight charges will reverse in Q3 as sea freight resumes').

## Standard Management Report Sections
1. Financial Performance Highlights.
2. Revenue & Commercial Momentum.
3. Gross Margin & Cost of Goods Analysis.
4. Operating Expenditure & Headcount Trends.
5. Cash Flow, Liquidity, and Runway.
6. Key Operational Risks & Corrective Measures.`
  },
  {
    agentName: "Lender and Investor Q&A Preparer",
    label: "Investor & Credit Facility Q&A Briefing",
    description: "Use when anticipating critical questions from lenders, equity investors, or credit rating analysts regarding financial results and guidance.",
    instructions: `## Purpose & Scope
Guides the preparation of executive Q&A briefing documents for quarterly earnings calls, lender compliance meetings, and investor roadshows.

## Anticipation & Question Formulation
1. **Identify Vulnerabilities & Outliers:**
   - Scan financial statements for metric anomalies: Margin compression, working capital deterioration, customer concentration shifts, one-off charges.
   - Formulate the sharpest, most probing version of the question an institutional investor or credit risk officer will ask.
2. **Answer Architecture:**
   - **Direct Answer First:** Provide a direct, unambiguous answer in the first sentence. Avoid evasion or corporate buzzwords.
   - **Supporting Quantified Evidence:** Provide 2-3 concrete data points supporting the position.
   - **Strategic Reassurance:** Reaffirm long-term guidance, capital allocation discipline, and risk mitigations.
3. **Lender Specific Areas:**
   - Covenant compliance margins, debt maturity profiles, liquidity headroom, interest rate hedging coverage.
4. **Equity Investor Specific Areas:**
   - Net revenue retention, customer churn, CAC efficiency, competitive moat, guidance adjustments.

## Deliverable
Deliver an Executive Q&A Brief: Question, Category, Probability (High/Med/Low), Core Talking Point, Detailed Factual Background, and What NOT to Say.`
  },
  {
    agentName: "Counterparty Financial Health Monitor",
    label: "Supplier & Customer Financial Distress Scoring",
    description: "Use when evaluating commercial counterparty financial health, calculating Altman Z-Scores, and monitoring public indicators of solvency risk.",
    instructions: `## Purpose & Scope
Standardizes the continuous monitoring and quantitative risk scoring of key suppliers and commercial customers to protect against counterparty insolvency.

## Quantitative Distress Models
1. **Altman Z-Score (Manufacturing & Non-Manufacturing Models):**
   - For Private Manufacturing Entities:
     \`Z' = 0.717*(Working Capital/Total Assets) + 0.847*(Retained Earnings/Total Assets) + 3.107*(EBIT/Total Assets) + 0.420*(Book Value Equity/Total Liabilities) + 0.998*(Sales/Total Assets)\`
   - Evaluation Zones:
     - \`Z' > 2.9\`: Safe Zone (Low risk of bankruptcy within 24 months).
     - \`1.23 < Z' < 2.9\`: Grey Zone (Moderate risk; heightened surveillance required).
     - \`Z' < 1.23\`: Distress Zone (High probability of default; take protective action).
2. **Qualitative & Early Warning Indicators:**
   - Supplier Indicators: Inability to meet delivery dates, requests for accelerated payment terms, sudden supplier management turnover, loss of credit insurance coverage.
   - Customer Indicators: Disputed invoices without clear basis, partial payments, bounced checks, deteriorating trade credit reference reports.

## Risk Mitigation Protocols
- For Critical Suppliers in Distress Zone: Identify alternative qualified vendors; secure safety inventory; evaluate escrow for key intellectual property.
- For Key Customers in Distress Zone: Reduce credit terms to Net 15 or Cash in Advance; require collateral or parent guarantee; enforce strict credit limits.`
  }
];
